USE MOVIES_DB;

-- SELECT

SELECT TITLE, AWARDS, ID FROM MOVIES;

SELECT * FROM SERIES WHERE GENRE_ID >= 4 ORDER BY TITLE DESC;

SELECT * FROM MOVIES WHERE AWARDS BETWEEN 3 AND 11;

SELECT * FROM MOVIES WHERE AWARDS IN(3,11,7) ORDER BY AWARDS;

SELECT * FROM MOVIES WHERE length IS NULL;

SELECT * FROM SERIES WHERE TITLE LIKE '%The%';

SELECT * FROM MOVIES WHERE TITLE LIKE '_a%' order by title DESC LIMIT 3;
